spring.application.name=WorkFlow
spring.datasource.url=jdbc:mysql://localhost:3306/workflow-schema?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=SecurePassword123
spring.jpa.hibernate.ddl-auto=update